version: '3.1'
name: beauf-king
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'testdatabase'
      POSTGRES_USER: 'testuser'
      POSTGRES_PASSWORD: 'Sc00b!d00'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - "./data:/var/lib/postgresql/data:rw"

  beauf-king:
    image: beauf-king-service
    ports:
      - 9292:8080
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/testdatabase
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.datasource.username=testuser
      - spring.datasource.password=Sc00b!d00
    depends_on:
      - db
